//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProjectInterview.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Registration
    {
        public int id { get; set; }

    [Display(Name="User ")]
    [Required]
        public string name { get; set; }

        [Display(Name = "  Number")]
        [Required]
        public string contact_number { get; set; }
        [Display(Name = "Email ")]
        [Required]
        [DataType(DataType.EmailAddress, ErrorMessage = "Error message.")]
        public string email { get; set; }

        [Display(Name = "Password ")]
        [Required]
        [DataType(DataType.Password)]
        public string password { get; set; }
        public Nullable<int> t_id { get; set; }
    
        public virtual Type_Login Type_Login { get; set; }
    }
}
